package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const Version = "dev"

func Main(args []string) error {
	if len(args) == 0 {
		printHelp()
		return nil
	}

	switch args[0] {
	case "help", "-h", "--help":
		printHelp()
		return nil
	case "version", "-v", "--version":
		fmt.Println(Version)
		return nil
	case "new":
		return runNew(args[1:])
	default:
		return fmt.Errorf("unknown command %q", args[0])
	}
}

func runNew(args []string) error {
	if len(args) == 0 {
		return errors.New("missing destination directory: quicframe new <dir>")
	}
	if len(args) > 1 {
		return errors.New("too many arguments: quicframe new <dir>")
	}

	dest := filepath.Clean(args[0])
	moduleName := sanitizeModuleName(filepath.Base(dest))
	if moduleName == "" {
		return fmt.Errorf("could not derive a module name from %q", args[0])
	}

	if err := os.MkdirAll(dest, 0o755); err != nil {
		return err
	}

	if err := writeNewFile(filepath.Join(dest, "go.mod"), starterGoMod(moduleName)); err != nil {
		return err
	}
	if err := writeNewFile(filepath.Join(dest, "main.go"), starterMainGo()); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(dest, ".local", "certs"), 0o755); err != nil {
		return err
	}
	if err := writeNewFile(filepath.Join(dest, ".gitignore"), starterGitIgnore()); err != nil {
		return err
	}
	if err := writeNewFile(filepath.Join(dest, "README.md"), starterREADME(moduleName)); err != nil {
		return err
	}

	fmt.Printf("Created QuicFrame app in %s\n", dest)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Printf("  cd %s\n", dest)
	fmt.Println("  go mod tidy")
	fmt.Println("  go run .")
	return nil
}

func writeNewFile(path, content string) error {
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%s already exists", path)
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func sanitizeModuleName(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	if name == "." || name == string(filepath.Separator) {
		return ""
	}

	var b strings.Builder
	prevDash := false
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
			prevDash = false
		case r >= '0' && r <= '9':
			b.WriteRune(r)
			prevDash = false
		case r == '-' || r == '_':
			if !prevDash && b.Len() > 0 {
				b.WriteByte('-')
				prevDash = true
			}
		}
	}

	return strings.Trim(b.String(), "-")
}

func printHelp() {
	fmt.Println(`QuicFrame CLI

Usage:
  quicframe <command>

Commands:
  new <dir>   Create a starter QuicFrame app
  version     Print CLI version
  help        Show this help

Install:
  go install github.com/msmecodex/quicframe@latest`)
}

func starterGoMod(moduleName string) string {
	return fmt.Sprintf(`module %s

go 1.24.0
`, moduleName)
}

func starterMainGo() string {
	return `package main

import (
	"context"
	"log"

	qf "github.com/msmecodex/quicframe/framework"
	"github.com/msmecodex/quicframe/middleware"
	"github.com/msmecodex/quicframe/tlsutil"
)

func main() {
	app := qf.New()
	app.Use(
		middleware.Recovery(),
		middleware.Logger(),
	)

	app.GET("/ping", func(c *qf.Context) error {
		return c.MsgPack(200, map[string]string{"pong": "ok"})
	})

	tlsCfg, err := tlsutil.LoadOrCreateSelfSigned(
		".local/certs/localhost-cert.pem",
		".local/certs/localhost-key.pem",
		"localhost",
		"127.0.0.1",
	)
	if err != nil {
		log.Fatal(err)
	}

	log.Println("QuicFrame server listening on :4433 and :4434")
	if err := app.ListenAddr(context.Background(), ":4433", ":4434", tlsCfg); err != nil {
		log.Fatal(err)
	}
}
`
}

func starterGitIgnore() string {
	return `.local/
`
}

func starterREADME(moduleName string) string {
	return fmt.Sprintf("# %s\n\nStarter app generated by QuicFrame CLI.\n\n## Run\n\n```bash\ngo mod tidy\ngo run .\n```\n\n## Endpoints\n\n- Native QUIC: `:4433`\n- WebTransport: `:4434` at `/wt`\n- Health check: `/ping`\n", moduleName)
}
